name: database

services:
  auth-pg:
    image: postgres:14-alpine3.17
    environment:
      POSTGRES_DB: ${PG_DATABASE:-}
      POSTGRES_USER: ${PG_USER:-}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-}
    ports:
      - mode: ingress
        target: ${PG_PORT:-}
        published: ${PG_EXT_PORT:-}
        protocol: tcp
    volumes:
     - type: volume
       source: auth-volume
       target: /var/lib/postgresql/data
    networks:
      - auth-network
    restart: on-failure

volumes:
  auth-volume:
    name: auth-database-volume

networks:
  auth-network:
    name: auth-app-network
    driver: default
