name: auth-db

services:
  auth-pg:
    image: postgres:14-alpine3.17
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=PG_DATABASE
      - POSTGRES_USER=PG_USER
      - POSTGRES_PASSWORD=PG_PASSWORD
      - POSTGRES_PORT=PG_PORT
    ports:
      - mode: ingress
        target: POSTGRES_PORT
        published: 54321
        protocol: tcp
    volumes:
     - type: volume
       source: auth-volume
       target: /var/lib/postgresql/data
    networks:
      - auth-network
    restart: on-failure

volumes:
  auth-volume:
    name: auth-database-volume

networks:
  auth-network:
    name: auth-app-network
